### ISSUE TITLE
表示关注

### ISSUE THREAD

**Issue by ysmintor** [listenzz/RxCommand#1]
用的是Rxjava2，还很多不理解。对于内存方面存在泄露什么会不会有问题。其它各使用方面还需要提供更多的Demo，不然这也只是demo，毕竟还有多少地方需要处理，否则官方的databinding难道都没有用处了吗？
对于自动化测试等等都要考虑成熟，否则不敢用于生产环境。

**Comment by listenzz** [comment]
正打算写一个完整的项目，这个RxCommand正在公司的两个项目使用。

**Comment by listenzz** [comment]
一个完整的项目已经有了，就是谷歌官方的 TODO APP, 我在 todo-mvvm-databinding 这个分支作了修改，单元测试也做了修改。改后的项目：
```
git clone git@github.com:listenzz/todo-android.git
git checkout todo-mvvm-rxcommand
```

**Comment by ysmintor** [comment]
好的，我clone下来学习！
