### ISSUE TITLE
代码可读性

### ISSUE THREAD

**Issue by BCsl** [listenzz/RxCommand#2]
太多的 `Observable` 、`Subject` 看得太缭乱了，囧。只能怪自己 RxJava 学好

**Comment by listenzz** [comment]
`RxJava` 的世界，就是 `Observable` 的世界。`RxCommand` 的意图是把原本一个简单的 pull 操作，例如从服务器拉取一个列表数据，分离出众多的关注点，譬如该操作是否可以执行，是否正在执行，执行是否成功等等。这个简单的 pull 操作返回的是一个 `Observable` ，我们通过 publish 操作符把它变成多路广播，这样不同的关注点就可以订阅同一个 pull 结果，不同的关注点通过 Rx 强大的操作符进行转换、组合出自己关心的结果，这些结果又以流（Observable）的形式存在。 

`RxCommand` 实现的过程中，使用到了 Rx 多种特性和操作符，理解起来确实比较困难。和我一起工作的小伙伴们也是花了一个下午才弄懂这个类。建议先理解 `enabled`、`executing`、`errors`、`executionObservables` 这些关注点的使用场景和方式，然后再理解 `RxCommand` 的实现方式。在这之后，若有更好的可读性实现方式，欢迎 PR。 

编写这个类的初衷是为了可以让 Android 和 iOS 开发一样，可以愉快地使用 MVVM。 因为我们之前的架构是 RxJava + MVP，一方面 MVP 实现起来比较繁琐，另一方面我们的网络请求结果是一个 `Observable`，依赖于网络请求的的业务层返回的结果也是一个 `Observable`，可是数据流到 Presenter 这里却停了下来，这让我们很不爽，我们希望数据可以一直流到 View，因此我们把架构改成了 RxJava + MVVM。`RxCommand` 就是 ViewModel 用来将视图层的请求转发到业务层，并且将业务层的结果以分离关注点的形式返回给视图层的桥梁。

**Comment by BCsl** [comment]
感谢分析，会按照你的思路去整理下思路

**Comment by listenzz** [comment]
RxCommand 重构了下，实现方式更合理了，同时添加了单元测试

**Comment by BCsl** [comment]
赞👍，昨天对着 RxJava 的 API 看了大半天终于有所顿悟，这两天有空再看看重构后的代码

**Comment by wangmuy** [comment]
挺赞的。同时能否考虑吸收一下这个c#版本的command？个人感觉c#的更全面一些
https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI/ReactiveCommand.cs

**Comment by listenzz** [comment]
@wangmuy 谢谢提供样本，近期会扩展一些功能，以更好地适应 Rxjava2
