### ISSUE TITLE
结合Google 207 IO大会的Architecture Components的想法

### ISSUE THREAD

**Issue by ysmintor** [listenzz/RxCommand#3]
Architecture Components 提出表明了官方一种立场，带来的ViewModel， LiveData等等组件简化了生命周期，RxCommand的功能好像可以结合。

**Comment by listenzz** [comment]
我们一直用的架构是 clean architecture，具体用什么样的库（架构组件）去实现这样的架构，我司也在不断探索和改进当中。官方这次提供的组件，值得了解。Room 支持 RxJava，如果项目当中使用了 RxJava，当然可以结合 RxCommand。官方认为如果使用了 RxJava，可以用 Observable 替换掉 LiveData。  Lifecycle Components 是个好东西。

**Comment by listenzz** [comment]
更新了 demo，使用了 LifecycleRegistryOwner 和 ViewModel 这两个官方组件，同时使得 Observable 是 lifecycle-aware 的，并且关于生命周期的行为表现和 LiveData 一致。
