### ISSUE TITLE
Kotlin 调用发现的问题: checkParameterIsNotNull

### ISSUE THREAD

**Issue by Blankeer** [listenzz/RxCommand#6]
```java
//定义
taskListCommand = RxCommand.create(object : io.reactivex.functions.Function<Any, Observable<NewsListResponse>> {
            override fun apply(t: Any): Observable<NewsListResponse> {
                return repo.getNewsList()
            }
        })
// 使用
taskListCommand
        .switchToLatest()
        .compose(Live.bindLifecycle(this@NewsListActivity))
        .subscribe({
           // ....
        })
taskListCommand.execute(null)
```
运行时报错:
`java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter t`

查了一下原因,因为 Kotlin 会强制检查 null 类型,
io.reactivex.functions.Function 的定义是
```
public interface Function<T, R> {
    @NonNull
    R apply(@NonNull T t) throws Exception;
}
```
参数 t 是 `@NonNull` 修饰
RxCommand#318 是这样写的:
```
    //省略不重要代码
    public final Observable<T> execute(@Nullable Object input) {
            Observable<T> observable = mFunc.apply(input);
            //.....
    }
```
这个参数 input 是`@Nullable`修饰,可为空,但是`mFunc.apply(input)` 这个 apply 方法参数是上面贴的 `@NonNull `修饰,当调用 `taskListCommand.execute(null)` 时, 这个 null 会传给 taskListCommand 的 create 里的 `override fun apply(t: Any): Observable<NewsListResponse>`方法,而这里t的定义是 `apply(t: Any)` 必须不能为空,我尝试过修改这里为 `override fun apply(t: Any?): Observable<NewsListResponse>`会提示没有复写父类方法.

目前的解决办法:  调用`taskListCommand.execute(null)`时不要传入 null, 随便传一个对象或者数字,就能解决.

希望能优化
😬

**Comment by listenzz** [comment]
好的，感谢指出。
